# Build the manager binary
FROM golang:1 AS builder
ARG TARGETOS
ARG TARGETARCH

WORKDIR /workspace
# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum

# Copy the go source
COPY cmd/ cmd/
COPY internal/ internal/
# Copy downloaded dependencies
# NOTE: run `go work vendor || go mod vendor` if dir does not exist
COPY vendor/ vendor/

# Build
# the GOARCH has not a default value to allow the binary be built according to the host where the command
# was called. For example, if we call make docker-build in a local env which has the Apple Silicon M1 SO
# the docker BUILDPLATFORM arg will be linux/arm64 when for Apple x86 it will be linux/amd64. Therefore,
# by leaving it empty we can ensure that the container and binary shipped on it will have the same platform.
RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -mod vendor -a -o exporter cmd/main.go

################################################################################

# Use distroless as minimal base image to package the manager binary
# Refer to https://github.com/GoogleContainerTools/distroless for more details
FROM gcr.io/distroless/static:nonroot

# OCI Annotations
# https://github.com/opencontainers/image-spec/blob/v1.0/annotations.md
LABEL org.opencontainers.image.authors="slinky@schedmd.com" \
      org.opencontainers.image.title="Slurm Exporter" \
      org.opencontainers.image.description="Prometheus collector and exporter for metrics extracted from Slurm" \
      org.opencontainers.image.documentation="https://github.com/SlinkyProject/slurm-exporter" \
      org.opencontainers.image.license="Apache-2.0" \
      org.opencontainers.image.vendor="SchedMD LLC." \
      org.opencontainers.image.version="v0.1.1" \
      org.opencontainers.image.source="https://github.com/SlinkyProject/slurm-exporter"

# HasRequiredLabel requirement from Red Hat OpenShift Software Certification
# https://access.redhat.com/documentation/en-us/red_hat_software_certification/2024/html/red_hat_openshift_software_certification_policy_guide/assembly-requirements-for-container-images_openshift-sw-cert-policy-introduction#con-image-metadata-requirements_openshift-sw-cert-policy-container-images
LABEL name="Slurm Exporter" \
      summary="Prometheus collector and exporter for metrics extracted from Slurm " \
      description="Prometheus collector and exporter for metrics extracted from Slurm" \
      vendor="SchedMD LLC." \
      version="v0.1.1" \
      release="https://github.com/SlinkyProject/slurm-exporter"

WORKDIR /
COPY --from=builder /workspace/ .
USER 65532:65532

ENTRYPOINT ["/exporter"]
